Hertzbert C., Stanley A., Neshma S., Fareha S., Cisse, S.

#4. PUMS Data
First, I'll start by loading the PUMS data which I have already extracted from the zip file and saved in the working directory where R is going to be looking. Then, I will check out the first ten rows and seven columns.

load("acs2017_ny_data.RData")
acs2017_ny[1:10,1:7]
##    AGE female educ_nohs educ_hs educ_somecoll educ_college educ_advdeg
## 1   72      1         0       0             0            0           1
## 2   72      0         0       0             0            0           1
## 3   31      0         0       0             0            1           0
## 4   28      1         0       0             0            1           0
## 5   54      0         0       0             0            0           1
## 6   45      1         0       1             0            0           0
## 7   84      1         0       0             1            0           0
## 8   71      0         0       0             0            1           0
## 9   68      1         0       0             1            0           0
## 10  37      1         1       0             0            0           0
Now, I will attach the the acs2017_ny database by using the attach() function. According to rdocumentation.org, doing this ensures that the database is attached to the R search path. This means that the database is searched by R when evaluating a variable, so objects in the database can be accessed by simply giving their names. Important to note that the attach() function has the side effect of altering the search path and this can easily lead to the wrong object of a particular name being found. People often forget to detach databases.

attach(acs2017_ny)
To find out more about the data in my database, I'll use the summary() function

summary(acs2017_ny)
##       AGE            female         educ_nohs        educ_hs      
##  Min.   : 0.00   Min.   :0.0000   Min.   :0.000   Min.   :0.0000  
##  1st Qu.:22.00   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000  
##  Median :42.00   Median :1.0000   Median :0.000   Median :0.0000  
##  Mean   :41.57   Mean   :0.5156   Mean   :0.271   Mean   :0.2804  
##  3rd Qu.:60.00   3rd Qu.:1.0000   3rd Qu.:1.000   3rd Qu.:1.0000  
##  Max.   :95.00   Max.   :1.0000   Max.   :1.000   Max.   :1.0000  
##                                                                   
##  educ_somecoll    educ_college     educ_advdeg                  SCHOOL      
##  Min.   :0.000   Min.   :0.0000   Min.   :0.000   N/A              :  5569  
##  1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.000   No, not in school:144968  
##  Median :0.000   Median :0.0000   Median :0.000   Yes, in school   : 46048  
##  Mean   :0.173   Mean   :0.1567   Mean   :0.119   Missing          :     0  
##  3rd Qu.:0.000   3rd Qu.:0.0000   3rd Qu.:0.000                             
##  Max.   :1.000   Max.   :1.0000   Max.   :1.000                             
##                                                                             
##                         EDUC      
##  Grade 12                 :55119  
##  4 years of college       :30802  
##  5+ years of college      :23385  
##  1 year of college        :19947  
##  Nursery school to grade 4:14240  
##  2 years of college       :14065  
##  (Other)                  :39027  
##                                           EDUCD      
##  Regular high school diploma                 :35689  
##  Bachelor's degree                           :30802  
##  1 or more years of college credit, no degree:19947  
##  Master's degree                             :17010  
##  Associate's degree, type not specified      :14065  
##  Some college, but less than 1 year          : 9086  
##  (Other)                                     :69986  
##                                      DEGFIELD     
##  N/A                                     :142398  
##  Business                                :  9802  
##  Education Administration and Teaching   :  6708  
##  Social Sciences                         :  4836  
##  Medical and Health Sciences and Services:  3919  
##  Fine Arts                               :  3491  
##  (Other)                                 : 25431  
##                                   DEGFIELDD     
##  N/A                                   :142398  
##  Psychology                            :  2926  
##  Business Management and Administration:  2501  
##  Accounting                            :  2284  
##  General Education                     :  2238  
##  English Language and Literature       :  2202  
##  (Other)                               : 42036  
##                                  DEGFIELD2     
##  N/A                                  :190425  
##  Business                             :   972  
##  Social Sciences                      :   853  
##  Education Administration and Teaching:   611  
##  Fine Arts                            :   465  
##  Communications                       :   352  
##  (Other)                              :  2907  
##                                                            DEGFIELD2D    
##  N/A                                                            :190425  
##  Psychology                                                     :   284  
##  Economics                                                      :   260  
##  Political Science and Government                               :   243  
##  Business Management and Administration                         :   217  
##  French, German, Latin and Other Common Foreign Language Studies:   205  
##  (Other)                                                        :  4951  
##       PUMA            GQ           OWNERSHP       OWNERSHPD        MORTGAGE    
##  Min.   : 100   Min.   :1.000   Min.   :0.000   Min.   : 0.00   Min.   :0.000  
##  1st Qu.:1500   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:12.00   1st Qu.:0.000  
##  Median :3201   Median :1.000   Median :1.000   Median :13.00   Median :1.000  
##  Mean   :2713   Mean   :1.148   Mean   :1.266   Mean   :14.95   Mean   :1.453  
##  3rd Qu.:3902   3rd Qu.:1.000   3rd Qu.:2.000   3rd Qu.:22.00   3rd Qu.:3.000  
##  Max.   :4114   Max.   :5.000   Max.   :2.000   Max.   :22.00   Max.   :4.000  
##                                                                                
##     OWNCOST           RENT         COSTELEC       COSTGAS        COSTWATR   
##  Min.   :    0   Min.   :   0   Min.   :   0   Min.   :   0   Min.   :   0  
##  1st Qu.: 1208   1st Qu.:   0   1st Qu.: 960   1st Qu.: 840   1st Qu.: 320  
##  Median : 2891   Median :   0   Median :1560   Median :2400   Median :1400  
##  Mean   :38582   Mean   : 393   Mean   :2311   Mean   :5032   Mean   :4836  
##  3rd Qu.:99999   3rd Qu.: 630   3rd Qu.:2520   3rd Qu.:9993   3rd Qu.:9993  
##  Max.   :99999   Max.   :3800   Max.   :9997   Max.   :9997   Max.   :9997  
##                                                                             
##     COSTFUEL       HHINCOME          FOODSTMP        LINGISOL    
##  Min.   :   0   Min.   : -11800   Min.   :1.000   Min.   :0.000  
##  1st Qu.:9993   1st Qu.:  41600   1st Qu.:1.000   1st Qu.:1.000  
##  Median :9993   Median :  81700   Median :1.000   Median :1.000  
##  Mean   :7935   Mean   : 114902   Mean   :1.147   Mean   :1.002  
##  3rd Qu.:9993   3rd Qu.: 140900   3rd Qu.:1.000   3rd Qu.:1.000  
##  Max.   :9997   Max.   :2030000   Max.   :2.000   Max.   :2.000  
##                 NA's   :10630                                    
##      ROOMS           BUILTYR2         UNITSSTR        FUELHEAT    
##  Min.   : 0.000   Min.   : 0.000   Min.   : 0.00   Min.   :0.000  
##  1st Qu.: 4.000   1st Qu.: 1.000   1st Qu.: 3.00   1st Qu.:2.000  
##  Median : 6.000   Median : 3.000   Median : 3.00   Median :2.000  
##  Mean   : 5.887   Mean   : 3.711   Mean   : 4.39   Mean   :2.959  
##  3rd Qu.: 8.000   3rd Qu.: 5.000   3rd Qu.: 6.00   3rd Qu.:4.000  
##  Max.   :16.000   Max.   :22.000   Max.   :10.00   Max.   :9.000  
##                                                                   
##       SSMC            FAMSIZE           NCHILD           NCHLT5       
##  Min.   :0.00000   Min.   : 1.000   Min.   :0.0000   Min.   :0.00000  
##  1st Qu.:0.00000   1st Qu.: 2.000   1st Qu.:0.0000   1st Qu.:0.00000  
##  Median :0.00000   Median : 3.000   Median :0.0000   Median :0.00000  
##  Mean   :0.01102   Mean   : 3.087   Mean   :0.5009   Mean   :0.08441  
##  3rd Qu.:0.00000   3rd Qu.: 4.000   3rd Qu.:1.0000   3rd Qu.:0.00000  
##  Max.   :2.00000   Max.   :19.000   Max.   :9.0000   Max.   :5.00000  
##                                                                       
##      RELATE          RELATED           MARST            RACE          RACED    
##  Min.   : 1.000   Min.   : 101.0   Min.   :1.000   Min.   :1.00   Min.   :100  
##  1st Qu.: 1.000   1st Qu.: 101.0   1st Qu.:1.000   1st Qu.:1.00   1st Qu.:100  
##  Median : 2.000   Median : 201.0   Median :5.000   Median :1.00   Median :100  
##  Mean   : 3.307   Mean   : 335.6   Mean   :3.742   Mean   :2.03   Mean   :205  
##  3rd Qu.: 3.000   3rd Qu.: 301.0   3rd Qu.:6.000   3rd Qu.:2.00   3rd Qu.:200  
##  Max.   :13.000   Max.   :1301.0   Max.   :6.000   Max.   :9.00   Max.   :990  
##                                                                                
##      HISPAN          HISPAND                  BPL        
##  Min.   :0.0000   Min.   :  0.00   New York     :128517  
##  1st Qu.:0.0000   1st Qu.:  0.00   West Indies  :  8481  
##  Median :0.0000   Median :  0.00   China        :  4964  
##  Mean   :0.4153   Mean   : 44.75   SOUTH AMERICA:  4957  
##  3rd Qu.:0.0000   3rd Qu.:  0.00   India        :  3476  
##  Max.   :4.0000   Max.   :498.00   Pennsylvania :  3303  
##                                    (Other)      : 42887  
##                  BPLD                            ANCESTR1    
##  New York          :128517   Not Reported            :32021  
##  China             :  4116   Italian                 :20577  
##  Dominican Republic:  3517   Irish, various subheads,:16388  
##  Pennsylvania      :  3303   German                  :12781  
##  New Jersey        :  3127   African-American        : 9559  
##  Puerto Rico       :  2272   United States           : 8209  
##  (Other)           : 51733   (Other)                 :97050  
##                                    ANCESTR1D             ANCESTR2     
##  Not Reported                           :32021   Not Reported:141487  
##  Italian (1990-2000, ACS, PRCS)         :20577   German      :  9476  
##  Irish                                  :15651   Irish       :  9238  
##  German (1990-2000, ACS/PRCS)           :12605   English     :  4895  
##  African-American (1990-2000, ACS, PRCS): 9559   Italian     :  4531  
##  United States                          : 8209   Polish      :  3113  
##  (Other)                                :97963   (Other)     : 23845  
##                           ANCESTR2D         CITIZEN          YRSUSA1      
##  Not Reported                  :141487   Min.   :0.0000   Min.   : 0.000  
##  German (1990-2000, ACS, PRCS) :  9441   1st Qu.:0.0000   1st Qu.: 0.000  
##  Irish                         :  8809   Median :0.0000   Median : 0.000  
##  English                       :  4895   Mean   :0.4793   Mean   : 5.377  
##  Italian (1990-2000, ACS, PRCS):  4531   3rd Qu.:0.0000   3rd Qu.: 0.000  
##  Polish                        :  3113   Max.   :3.0000   Max.   :92.000  
##  (Other)                       : 24309                                    
##     HCOVANY         HCOVPRIV         SEX            EMPSTAT     
##  Min.   :1.000   Min.   :1.000   Male  : 95222   Min.   :0.000  
##  1st Qu.:2.000   1st Qu.:1.000   Female:101363   1st Qu.:1.000  
##  Median :2.000   Median :2.000                   Median :1.000  
##  Mean   :1.951   Mean   :1.691                   Mean   :1.514  
##  3rd Qu.:2.000   3rd Qu.:2.000                   3rd Qu.:3.000  
##  Max.   :2.000   Max.   :2.000                   Max.   :3.000  
##                                                                 
##     EMPSTATD        LABFORCE          OCC              IND       
##  Min.   : 0.00   Min.   :0.000   0      : 79987   0      :79987  
##  1st Qu.:10.00   1st Qu.:1.000   2310   :  3494   7860   : 9025  
##  Median :10.00   Median :2.000   5700   :  3235   8680   : 6354  
##  Mean   :15.16   Mean   :1.331   430    :  3025   770    : 6279  
##  3rd Qu.:30.00   3rd Qu.:2.000   4720   :  2666   8190   : 5873  
##  Max.   :30.00   Max.   :2.000   4760   :  2563   7870   : 4041  
##                                  (Other):101615   (Other):85026  
##     CLASSWKR       CLASSWKRD        WKSWORK2        UHRSWORK    
##  Min.   :0.000   Min.   : 0.00   Min.   :0.000   Min.   : 0.00  
##  1st Qu.:0.000   1st Qu.: 0.00   1st Qu.:0.000   1st Qu.: 0.00  
##  Median :2.000   Median :22.00   Median :1.000   Median :12.00  
##  Mean   :1.116   Mean   :13.03   Mean   :2.701   Mean   :19.77  
##  3rd Qu.:2.000   3rd Qu.:22.00   3rd Qu.:6.000   3rd Qu.:40.00  
##  Max.   :2.000   Max.   :29.00   Max.   :6.000   Max.   :99.00  
##                                                                 
##      INCTOT           FTOTINC           INCWAGE          POVERTY     
##  Min.   :  -7300   Min.   : -11800   Min.   :     0   Min.   :  0.0  
##  1st Qu.:   8000   1st Qu.:  35550   1st Qu.:     0   1st Qu.:159.0  
##  Median :  25000   Median :  74000   Median : 10000   Median :351.0  
##  Mean   :  45245   Mean   : 107111   Mean   : 33796   Mean   :318.7  
##  3rd Qu.:  56500   3rd Qu.: 132438   3rd Qu.: 47000   3rd Qu.:501.0  
##  Max.   :1563000   Max.   :2030000   Max.   :638000   Max.   :501.0  
##  NA's   :31129     NA's   :10817     NA's   :33427                   
##     MIGRATE1       MIGRATE1D        MIGPLAC1         MIGCOUNTY1     
##  Min.   :0.000   Min.   : 0.00   Min.   :  0.000   Min.   :  0.000  
##  1st Qu.:1.000   1st Qu.:10.00   1st Qu.:  0.000   1st Qu.:  0.000  
##  Median :1.000   Median :10.00   Median :  0.000   Median :  0.000  
##  Mean   :1.122   Mean   :11.51   Mean   :  6.184   Mean   :  4.117  
##  3rd Qu.:1.000   3rd Qu.:10.00   3rd Qu.:  0.000   3rd Qu.:  0.000  
##  Max.   :4.000   Max.   :40.00   Max.   :900.000   Max.   :810.000  
##                                                                     
##     MIGPUMA1        VETSTAT          VETSTATD         PWPUMA00    
##  Min.   :    0   Min.   :0.0000   Min.   : 0.000   Min.   :    0  
##  1st Qu.:    0   1st Qu.:1.0000   1st Qu.:11.000   1st Qu.:    0  
##  Median :    0   Median :1.0000   Median :11.000   Median :    0  
##  Mean   :  277   Mean   :0.8621   Mean   : 9.412   Mean   : 1255  
##  3rd Qu.:    0   3rd Qu.:1.0000   3rd Qu.:11.000   3rd Qu.: 3100  
##  Max.   :70100   Max.   :2.0000   Max.   :20.000   Max.   :59300  
##                                                                   
##     TRANWORK         TRANTIME         DEPARTS           in_NYC      
##  Min.   : 0.000   Min.   :  0.00   Min.   :   0.0   Min.   :0.0000  
##  1st Qu.: 0.000   1st Qu.:  0.00   1st Qu.:   0.0   1st Qu.:0.0000  
##  Median : 0.000   Median :  0.00   Median :   0.0   Median :0.0000  
##  Mean   : 9.725   Mean   : 14.75   Mean   : 373.3   Mean   :0.3615  
##  3rd Qu.:10.000   3rd Qu.: 20.00   3rd Qu.: 732.0   3rd Qu.:1.0000  
##  Max.   :70.000   Max.   :138.00   Max.   :2345.0   Max.   :1.0000  
##                                                                     
##     in_Bronx       in_Manhattan       in_StatenI       in_Brooklyn   
##  Min.   :0.0000   Min.   :0.00000   Min.   :0.00000   Min.   :0.000  
##  1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.000  
##  Median :0.0000   Median :0.00000   Median :0.00000   Median :0.000  
##  Mean   :0.0538   Mean   :0.04981   Mean   :0.02084   Mean   :0.126  
##  3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.000  
##  Max.   :1.0000   Max.   :1.00000   Max.   :1.00000   Max.   :1.000  
##                                                                      
##    in_Queens      in_Westchester      in_Nassau          Hispanic     
##  Min.   :0.0000   Min.   :0.00000   Min.   :0.00000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.0000  
##  Median :0.0000   Median :0.00000   Median :0.00000   Median :0.0000  
##  Mean   :0.1111   Mean   :0.04413   Mean   :0.07032   Mean   :0.1387  
##  3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.0000  
##  Max.   :1.0000   Max.   :1.00000   Max.   :1.00000   Max.   :1.0000  
##                                                                       
##     Hisp_Mex          Hisp_PR         Hisp_Cuban         Hisp_DomR      
##  Min.   :0.00000   Min.   :0.0000   Min.   :0.000000   Min.   :0.00000  
##  1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.000000   1st Qu.:0.00000  
##  Median :0.00000   Median :0.0000   Median :0.000000   Median :0.00000  
##  Mean   :0.01626   Mean   :0.0436   Mean   :0.003403   Mean   :0.02827  
##  3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.000000   3rd Qu.:0.00000  
##  Max.   :1.00000   Max.   :1.0000   Max.   :1.000000   Max.   :1.00000  
##                                                                         
##      white             AfAm          Amindian            Asian        
##  Min.   :0.0000   Min.   :0.000   Min.   :0.000000   Min.   :0.00000  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.000000   1st Qu.:0.00000  
##  Median :1.0000   Median :0.000   Median :0.000000   Median :0.00000  
##  Mean   :0.6997   Mean   :0.125   Mean   :0.003779   Mean   :0.08656  
##  3rd Qu.:1.0000   3rd Qu.:0.000   3rd Qu.:0.000000   3rd Qu.:0.00000  
##  Max.   :1.0000   Max.   :1.000   Max.   :1.000000   Max.   :1.00000  
##                                                                       
##     race_oth        unmarried       veteran        has_AnyHealthIns
##  Min.   :0.0000   Min.   :0.00   Min.   :0.00000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.00   1st Qu.:0.00000   1st Qu.:1.0000  
##  Median :0.0000   Median :0.00   Median :0.00000   Median :1.0000  
##  Mean   :0.1324   Mean   :0.45   Mean   :0.04443   Mean   :0.9513  
##  3rd Qu.:0.0000   3rd Qu.:1.00   3rd Qu.:0.00000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.00   Max.   :1.00000   Max.   :1.0000  
##                                                                    
##  has_PvtHealthIns  Commute_car      Commute_bus      Commute_subway   
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000  
##  Median :1.0000   Median :0.0000   Median :0.00000   Median :0.00000  
##  Mean   :0.6906   Mean   :0.2997   Mean   :0.02162   Mean   :0.07468  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:0.00000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.00000   Max.   :1.00000  
##                                                                       
##   Commute_rail     Commute_other     below_povertyline below_150poverty
##  Min.   :0.00000   Min.   :0.00000   Min.   :0.000     Min.   :0.0000  
##  1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.000     1st Qu.:0.0000  
##  Median :0.00000   Median :0.00000   Median :0.000     Median :0.0000  
##  Mean   :0.01332   Mean   :0.05506   Mean   :0.122     Mean   :0.1965  
##  3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.000     3rd Qu.:0.0000  
##  Max.   :1.00000   Max.   :1.00000   Max.   :1.000     Max.   :1.0000  
##                                                                        
##  below_200poverty   foodstamps    
##  Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.0000   Median :0.0000  
##  Mean   :0.2676   Mean   :0.1465  
##  3rd Qu.:1.0000   3rd Qu.:0.0000  
##  Max.   :1.0000   Max.   :1.0000  
## 
Also, to find out the number of people in the dataset, I can use the length() function. In this case, i have ascribed it to a variable called NN_obs. Printing that variable shows us that there are 196,585 people in this dataset.

print(NN_obs <- length(AGE))
## [1] 196585
Let’s attempt to do some simple stats with this data In many instances, there are several ways to calculate the same thing in R. For instance, to calculate and compare the averages between the ages of men and women, I could use the summary()function, or I could use command functions like mean() and sd(). In my coding below, I would be using the female dummy variable (female == 1) to represent females in the data and using the logical not (!female) to represent males. Even though, I believe using female == 0 would also be suitable to represent men.

summary(AGE[female == 1])
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00   23.00   44.00   42.72   61.00   95.00
summary(AGE[!female])
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00   21.00   40.00   40.35   59.00   95.00
mean(AGE[female == 1])
## [1] 42.71629
sd(AGE[female == 1])
## [1] 23.72012
mean(AGE[!female])
## [1] 40.35398
sd(AGE[!female])
## [1] 23.1098

#3. Dice Experiment
Initial Roll - Dice Intact				Adjusted Dice				 2nd Attempt - Adjusted Dice		
1 = YES	0 = NO		              	1 = YES	0 = NO		   	1 = YES	0 = NO	
1				                          0			              	0		
0				                          0				              0		
0				                          0				              0		
0				                          0				              0		
0				                          0			              	0		
0				                          1				              0		
0				                          0				              0		
0				                          0				              0		
0				                          0				              0		
0				                          0				              0		
0				                          0			              	0		
0				                          0				              0		
0				                          0				              0		
0				                          0			              	0		
0				                          0				              0		
1				                          0				              0		
0				                          0				              0		
0				                          0				              1		
0				                          0				              1		
0				                          0			              	0		

After rolling the dice a total of 60 times, 20 on the initial set of rolls in which I had not tampered with the dice and 40 after melting 2 corners of the dice, I noticed that the events in which a 6 was rolled stayed relatively the same. I altered the dice in a very nonspecific way (in that my alteration was done to neither aid nor hinder the frequency in which a 6 was the outcome of my rolling the dice), so that led me to believe that there is still an even chance for a 6 to be my outcome on any given roll. The probability did not change (was not more or less often) as a result of my altering the dice. My assumption of "more or less often" would be anything noticably greater or less than 10%, as that is the average percentage for rolling a 6 in my first set of observations (untampered dice).My question now becomes, if I increased my number of rolls, would that bring me closer to the same value as 1/6 or .17? This is in relation to the law of large numbers.
The code we can write for a fair roll is sample(x = 1:6, size = 20, replace = TRUE)


#5. S&P 500 Data
Date	           Adj Close	            Change %
9/16/2019	      2997.959961	            -0.31%
9/17/2019	      3005.699951	             0.26%
9/18/2019	      3006.72998	             0.03%
9/19/2019	      3006.790039	             0.00%
9/20/2019	      2992.070068	            -0.49%
9/23/2019	      2991.780029	            -0.01%
9/24/2019	      2966.600098	            -0.84%
9/25/2019	      2984.870117	             0.62%
9/26/2019	      2977.620117	            -0.24%
9/27/2019	      2961.790039	            -0.53%
9/30/2019	      2976.73999	             0.50%
10/1/2019	      2940.25	                -1.23%
10/2/2019	      2887.610107	            -1.79%
10/3/2019	      2910.629883	             0.80%
10/4/2019	      2952.01001	             1.42%
10/7/2019	      2938.790039	            -0.45%
10/8/2019	      2893.060059	            -1.56%
10/9/2019	      2919.399902	             0.91%
10/10/2019	    2938.129883	             0.64%
10/11/2019	    2970.27002	             1.09%

2989.19104 =	Late September Average Closing

2932.688989	= Early October Average Closing
	
-1.890212096 =	Average Return for First 2 Weeks of October

0.296696091 =	Average Return On Days in which Previous Day was Positive

0.323031297 =	Average Return on Days in which 2 Previous Days were Positive

-0.226798099 =	Average Return on Days in which Previous Day was Negative

I chose to analyze the S&P 500 for September 30 - October 11, 2019. In a sense, I believe the "hot hands fallacy" only
helps in investment strategy if individuals realize that it is indeed a fallacy and nothing more. The hot hand (in terms of investing) is a phenomenon .. and nothing more. In terms of sports, I believe the "hot hand" is a bit more applicable to analyses, but biases (selection bias, confirmation bias, etc.) still occur. WIth that said, when it comes to investing, I believe these biases are exacerbated and thus the hot hand is not realistic. 